/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardExperienceRouteImport } from './routes/dashboard.experience'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard.testimonials'
import { Route as PUsernameRouteImport } from './routes/p.$username'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth.callback.$provider'
import { Route as DashboardBlogIndexRouteImport } from './routes/dashboard.blog.index'
import { Route as DashboardBlogNewRouteImport } from './routes/dashboard.blog.new'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardProjectsIdRouteImport } from './routes/dashboard.projects.$id'
import { Route as PUsernameProfileSlugRouteImport } from './routes/p.$username.$profileSlug'
import { Route as DashboardBlogIdEditRouteImport } from './routes/dashboard.blog.$id.edit'
import { Route as PUsernameProfileSlugBlogRouteImport } from './routes/p.$username.$profileSlug.blog'
import { Route as PUsernameProfileSlugBlogSlugRouteImport } from './routes/p.$username.$profileSlug.blog.$slug'
import { Route as PUsernameProfileSlugProjectsSlugRouteImport } from './routes/p.$username.$profileSlug.projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExperienceRoute = DashboardExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => DashboardRoute,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBlogIndexRoute = DashboardBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogNewRoute = DashboardBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const PUsernameProfileSlugRoute = PUsernameProfileSlugRouteImport.update({
  id: '/$profileSlug',
  path: '/$profileSlug',
  getParentRoute: () => PUsernameRoute,
} as any)
const DashboardBlogIdEditRoute = DashboardBlogIdEditRouteImport.update({
  id: '/blog/$id/edit',
  path: '/blog/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const PUsernameProfileSlugBlogRoute =
  PUsernameProfileSlugBlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => PUsernameProfileSlugRoute,
  } as any)
const PUsernameProfileSlugBlogSlugRoute =
  PUsernameProfileSlugBlogSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PUsernameProfileSlugBlogRoute,
  } as any)
const PUsernameProfileSlugProjectsSlugRoute =
  PUsernameProfileSlugProjectsSlugRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => PUsernameProfileSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/p/$username/$profileSlug': typeof PUsernameProfileSlugRouteWithChildren
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/blog/$id/edit': typeof DashboardBlogIdEditRoute
  '/p/$username/$profileSlug/blog': typeof PUsernameProfileSlugBlogRouteWithChildren
  '/p/$username/$profileSlug/blog/$slug': typeof PUsernameProfileSlugBlogSlugRoute
  '/p/$username/$profileSlug/projects/$slug': typeof PUsernameProfileSlugProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/p/$username/$profileSlug': typeof PUsernameProfileSlugRouteWithChildren
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/blog/$id/edit': typeof DashboardBlogIdEditRoute
  '/p/$username/$profileSlug/blog': typeof PUsernameProfileSlugBlogRouteWithChildren
  '/p/$username/$profileSlug/blog/$slug': typeof PUsernameProfileSlugBlogSlugRoute
  '/p/$username/$profileSlug/projects/$slug': typeof PUsernameProfileSlugProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/p/$username/$profileSlug': typeof PUsernameProfileSlugRouteWithChildren
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/blog/$id/edit': typeof DashboardBlogIdEditRoute
  '/p/$username/$profileSlug/blog': typeof PUsernameProfileSlugBlogRouteWithChildren
  '/p/$username/$profileSlug/blog/$slug': typeof PUsernameProfileSlugBlogSlugRoute
  '/p/$username/$profileSlug/projects/$slug': typeof PUsernameProfileSlugProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/experience'
    | '/dashboard/settings'
    | '/dashboard/testimonials'
    | '/p/$username'
    | '/dashboard/'
    | '/auth/callback/$provider'
    | '/dashboard/blog/new'
    | '/dashboard/projects/$id'
    | '/p/$username/$profileSlug'
    | '/dashboard/blog/'
    | '/dashboard/projects/'
    | '/dashboard/blog/$id/edit'
    | '/p/$username/$profileSlug/blog'
    | '/p/$username/$profileSlug/blog/$slug'
    | '/p/$username/$profileSlug/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/experience'
    | '/dashboard/settings'
    | '/dashboard/testimonials'
    | '/p/$username'
    | '/dashboard'
    | '/auth/callback/$provider'
    | '/dashboard/blog/new'
    | '/dashboard/projects/$id'
    | '/p/$username/$profileSlug'
    | '/dashboard/blog'
    | '/dashboard/projects'
    | '/dashboard/blog/$id/edit'
    | '/p/$username/$profileSlug/blog'
    | '/p/$username/$profileSlug/blog/$slug'
    | '/p/$username/$profileSlug/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/experience'
    | '/dashboard/settings'
    | '/dashboard/testimonials'
    | '/p/$username'
    | '/dashboard/'
    | '/auth/callback/$provider'
    | '/dashboard/blog/new'
    | '/dashboard/projects/$id'
    | '/p/$username/$profileSlug'
    | '/dashboard/blog/'
    | '/dashboard/projects/'
    | '/dashboard/blog/$id/edit'
    | '/p/$username/$profileSlug/blog'
    | '/p/$username/$profileSlug/blog/$slug'
    | '/p/$username/$profileSlug/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PUsernameRoute: typeof PUsernameRouteWithChildren
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/experience': {
      id: '/dashboard/experience'
      path: '/experience'
      fullPath: '/dashboard/experience'
      preLoaderRoute: typeof DashboardExperienceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/blog/': {
      id: '/dashboard/blog/'
      path: '/blog'
      fullPath: '/dashboard/blog/'
      preLoaderRoute: typeof DashboardBlogIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blog/new': {
      id: '/dashboard/blog/new'
      path: '/blog/new'
      fullPath: '/dashboard/blog/new'
      preLoaderRoute: typeof DashboardBlogNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$username/$profileSlug': {
      id: '/p/$username/$profileSlug'
      path: '/$profileSlug'
      fullPath: '/p/$username/$profileSlug'
      preLoaderRoute: typeof PUsernameProfileSlugRouteImport
      parentRoute: typeof PUsernameRoute
    }
    '/dashboard/blog/$id/edit': {
      id: '/dashboard/blog/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/dashboard/blog/$id/edit'
      preLoaderRoute: typeof DashboardBlogIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$username/$profileSlug/blog': {
      id: '/p/$username/$profileSlug/blog'
      path: '/blog'
      fullPath: '/p/$username/$profileSlug/blog'
      preLoaderRoute: typeof PUsernameProfileSlugBlogRouteImport
      parentRoute: typeof PUsernameProfileSlugRoute
    }
    '/p/$username/$profileSlug/blog/$slug': {
      id: '/p/$username/$profileSlug/blog/$slug'
      path: '/$slug'
      fullPath: '/p/$username/$profileSlug/blog/$slug'
      preLoaderRoute: typeof PUsernameProfileSlugBlogSlugRouteImport
      parentRoute: typeof PUsernameProfileSlugBlogRoute
    }
    '/p/$username/$profileSlug/projects/$slug': {
      id: '/p/$username/$profileSlug/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/p/$username/$profileSlug/projects/$slug'
      preLoaderRoute: typeof PUsernameProfileSlugProjectsSlugRouteImport
      parentRoute: typeof PUsernameProfileSlugRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardExperienceRoute: typeof DashboardExperienceRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBlogNewRoute: typeof DashboardBlogNewRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
  DashboardBlogIndexRoute: typeof DashboardBlogIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardBlogIdEditRoute: typeof DashboardBlogIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardExperienceRoute: DashboardExperienceRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBlogNewRoute: DashboardBlogNewRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
  DashboardBlogIndexRoute: DashboardBlogIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardBlogIdEditRoute: DashboardBlogIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PUsernameProfileSlugBlogRouteChildren {
  PUsernameProfileSlugBlogSlugRoute: typeof PUsernameProfileSlugBlogSlugRoute
}

const PUsernameProfileSlugBlogRouteChildren: PUsernameProfileSlugBlogRouteChildren =
  {
    PUsernameProfileSlugBlogSlugRoute: PUsernameProfileSlugBlogSlugRoute,
  }

const PUsernameProfileSlugBlogRouteWithChildren =
  PUsernameProfileSlugBlogRoute._addFileChildren(
    PUsernameProfileSlugBlogRouteChildren,
  )

interface PUsernameProfileSlugRouteChildren {
  PUsernameProfileSlugBlogRoute: typeof PUsernameProfileSlugBlogRouteWithChildren
  PUsernameProfileSlugProjectsSlugRoute: typeof PUsernameProfileSlugProjectsSlugRoute
}

const PUsernameProfileSlugRouteChildren: PUsernameProfileSlugRouteChildren = {
  PUsernameProfileSlugBlogRoute: PUsernameProfileSlugBlogRouteWithChildren,
  PUsernameProfileSlugProjectsSlugRoute: PUsernameProfileSlugProjectsSlugRoute,
}

const PUsernameProfileSlugRouteWithChildren =
  PUsernameProfileSlugRoute._addFileChildren(PUsernameProfileSlugRouteChildren)

interface PUsernameRouteChildren {
  PUsernameProfileSlugRoute: typeof PUsernameProfileSlugRouteWithChildren
}

const PUsernameRouteChildren: PUsernameRouteChildren = {
  PUsernameProfileSlugRoute: PUsernameProfileSlugRouteWithChildren,
}

const PUsernameRouteWithChildren = PUsernameRoute._addFileChildren(
  PUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PUsernameRoute: PUsernameRouteWithChildren,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
