/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PUsernameRouteImport } from './routes/p.$username'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard.testimonials'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardExperienceRouteImport } from './routes/dashboard.experience'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardBlogIndexRouteImport } from './routes/dashboard.blog.index'
import { Route as PUsernameBlogRouteImport } from './routes/p.$username.blog'
import { Route as DashboardProjectsIdRouteImport } from './routes/dashboard.projects.$id'
import { Route as DashboardBlogNewRouteImport } from './routes/dashboard.blog.new'
import { Route as PUsernameProjectsSlugRouteImport } from './routes/p.$username.projects.$slug'
import { Route as PUsernameBlogSlugRouteImport } from './routes/p.$username.blog.$slug'
import { Route as DashboardBlogIdEditRouteImport } from './routes/dashboard.blog.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExperienceRoute = DashboardExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogIndexRoute = DashboardBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => DashboardRoute,
} as any)
const PUsernameBlogRoute = PUsernameBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PUsernameRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogNewRoute = DashboardBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => DashboardRoute,
} as any)
const PUsernameProjectsSlugRoute = PUsernameProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => PUsernameRoute,
} as any)
const PUsernameBlogSlugRoute = PUsernameBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PUsernameBlogRoute,
} as any)
const DashboardBlogIdEditRoute = DashboardBlogIdEditRouteImport.update({
  id: '/blog/$id/edit',
  path: '/blog/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/p/$username/blog': typeof PUsernameBlogRouteWithChildren
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/blog/$id/edit': typeof DashboardBlogIdEditRoute
  '/p/$username/blog/$slug': typeof PUsernameBlogSlugRoute
  '/p/$username/projects/$slug': typeof PUsernameProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/p/$username/blog': typeof PUsernameBlogRouteWithChildren
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/blog/$id/edit': typeof DashboardBlogIdEditRoute
  '/p/$username/blog/$slug': typeof PUsernameBlogSlugRoute
  '/p/$username/projects/$slug': typeof PUsernameProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/p/$username/blog': typeof PUsernameBlogRouteWithChildren
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/blog/$id/edit': typeof DashboardBlogIdEditRoute
  '/p/$username/blog/$slug': typeof PUsernameBlogSlugRoute
  '/p/$username/projects/$slug': typeof PUsernameProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/experience'
    | '/dashboard/settings'
    | '/dashboard/testimonials'
    | '/p/$username'
    | '/dashboard/'
    | '/dashboard/blog/new'
    | '/dashboard/projects/$id'
    | '/p/$username/blog'
    | '/dashboard/blog/'
    | '/dashboard/projects/'
    | '/dashboard/blog/$id/edit'
    | '/p/$username/blog/$slug'
    | '/p/$username/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/experience'
    | '/dashboard/settings'
    | '/dashboard/testimonials'
    | '/p/$username'
    | '/dashboard'
    | '/dashboard/blog/new'
    | '/dashboard/projects/$id'
    | '/p/$username/blog'
    | '/dashboard/blog'
    | '/dashboard/projects'
    | '/dashboard/blog/$id/edit'
    | '/p/$username/blog/$slug'
    | '/p/$username/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/experience'
    | '/dashboard/settings'
    | '/dashboard/testimonials'
    | '/p/$username'
    | '/dashboard/'
    | '/dashboard/blog/new'
    | '/dashboard/projects/$id'
    | '/p/$username/blog'
    | '/dashboard/blog/'
    | '/dashboard/projects/'
    | '/dashboard/blog/$id/edit'
    | '/p/$username/blog/$slug'
    | '/p/$username/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PUsernameRoute: typeof PUsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/experience': {
      id: '/dashboard/experience'
      path: '/experience'
      fullPath: '/dashboard/experience'
      preLoaderRoute: typeof DashboardExperienceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blog/': {
      id: '/dashboard/blog/'
      path: '/blog'
      fullPath: '/dashboard/blog/'
      preLoaderRoute: typeof DashboardBlogIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$username/blog': {
      id: '/p/$username/blog'
      path: '/blog'
      fullPath: '/p/$username/blog'
      preLoaderRoute: typeof PUsernameBlogRouteImport
      parentRoute: typeof PUsernameRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blog/new': {
      id: '/dashboard/blog/new'
      path: '/blog/new'
      fullPath: '/dashboard/blog/new'
      preLoaderRoute: typeof DashboardBlogNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$username/projects/$slug': {
      id: '/p/$username/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/p/$username/projects/$slug'
      preLoaderRoute: typeof PUsernameProjectsSlugRouteImport
      parentRoute: typeof PUsernameRoute
    }
    '/p/$username/blog/$slug': {
      id: '/p/$username/blog/$slug'
      path: '/$slug'
      fullPath: '/p/$username/blog/$slug'
      preLoaderRoute: typeof PUsernameBlogSlugRouteImport
      parentRoute: typeof PUsernameBlogRoute
    }
    '/dashboard/blog/$id/edit': {
      id: '/dashboard/blog/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/dashboard/blog/$id/edit'
      preLoaderRoute: typeof DashboardBlogIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardExperienceRoute: typeof DashboardExperienceRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBlogNewRoute: typeof DashboardBlogNewRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
  DashboardBlogIndexRoute: typeof DashboardBlogIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardBlogIdEditRoute: typeof DashboardBlogIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardExperienceRoute: DashboardExperienceRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBlogNewRoute: DashboardBlogNewRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
  DashboardBlogIndexRoute: DashboardBlogIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardBlogIdEditRoute: DashboardBlogIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PUsernameBlogRouteChildren {
  PUsernameBlogSlugRoute: typeof PUsernameBlogSlugRoute
}

const PUsernameBlogRouteChildren: PUsernameBlogRouteChildren = {
  PUsernameBlogSlugRoute: PUsernameBlogSlugRoute,
}

const PUsernameBlogRouteWithChildren = PUsernameBlogRoute._addFileChildren(
  PUsernameBlogRouteChildren,
)

interface PUsernameRouteChildren {
  PUsernameBlogRoute: typeof PUsernameBlogRouteWithChildren
  PUsernameProjectsSlugRoute: typeof PUsernameProjectsSlugRoute
}

const PUsernameRouteChildren: PUsernameRouteChildren = {
  PUsernameBlogRoute: PUsernameBlogRouteWithChildren,
  PUsernameProjectsSlugRoute: PUsernameProjectsSlugRoute,
}

const PUsernameRouteWithChildren = PUsernameRoute._addFileChildren(
  PUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PUsernameRoute: PUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
