/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PUsernameRouteImport } from './routes/p.$username'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard.testimonials'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardExperienceRouteImport } from './routes/dashboard.experience'
import { Route as DashboardBlogRouteImport } from './routes/dashboard.blog'
import { Route as DashboardProjectsIdRouteImport } from './routes/dashboard.projects.$id'
import { Route as DashboardBlogNewRouteImport } from './routes/dashboard.blog.new'
import { Route as PUsernameProjectsSlugRouteImport } from './routes/p.$username.projects.$slug'
import { Route as DashboardBlogIdEditRouteImport } from './routes/dashboard.blog.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExperienceRoute = DashboardExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogRoute = DashboardBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardBlogNewRoute = DashboardBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardBlogRoute,
} as any)
const PUsernameProjectsSlugRoute = PUsernameProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => PUsernameRoute,
} as any)
const DashboardBlogIdEditRoute = DashboardBlogIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => DashboardBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/blog': typeof DashboardBlogRouteWithChildren
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/blog/$id/edit': typeof DashboardBlogIdEditRoute
  '/p/$username/projects/$slug': typeof PUsernameProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/blog': typeof DashboardBlogRouteWithChildren
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/blog/$id/edit': typeof DashboardBlogIdEditRoute
  '/p/$username/projects/$slug': typeof PUsernameProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/blog': typeof DashboardBlogRouteWithChildren
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/p/$username': typeof PUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/blog/$id/edit': typeof DashboardBlogIdEditRoute
  '/p/$username/projects/$slug': typeof PUsernameProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/blog'
    | '/dashboard/experience'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/testimonials'
    | '/p/$username'
    | '/dashboard/'
    | '/dashboard/blog/new'
    | '/dashboard/projects/$id'
    | '/dashboard/blog/$id/edit'
    | '/p/$username/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/blog'
    | '/dashboard/experience'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/testimonials'
    | '/p/$username'
    | '/dashboard'
    | '/dashboard/blog/new'
    | '/dashboard/projects/$id'
    | '/dashboard/blog/$id/edit'
    | '/p/$username/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/blog'
    | '/dashboard/experience'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/testimonials'
    | '/p/$username'
    | '/dashboard/'
    | '/dashboard/blog/new'
    | '/dashboard/projects/$id'
    | '/dashboard/blog/$id/edit'
    | '/p/$username/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PUsernameRoute: typeof PUsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/experience': {
      id: '/dashboard/experience'
      path: '/experience'
      fullPath: '/dashboard/experience'
      preLoaderRoute: typeof DashboardExperienceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blog': {
      id: '/dashboard/blog'
      path: '/blog'
      fullPath: '/dashboard/blog'
      preLoaderRoute: typeof DashboardBlogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/blog/new': {
      id: '/dashboard/blog/new'
      path: '/new'
      fullPath: '/dashboard/blog/new'
      preLoaderRoute: typeof DashboardBlogNewRouteImport
      parentRoute: typeof DashboardBlogRoute
    }
    '/p/$username/projects/$slug': {
      id: '/p/$username/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/p/$username/projects/$slug'
      preLoaderRoute: typeof PUsernameProjectsSlugRouteImport
      parentRoute: typeof PUsernameRoute
    }
    '/dashboard/blog/$id/edit': {
      id: '/dashboard/blog/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/blog/$id/edit'
      preLoaderRoute: typeof DashboardBlogIdEditRouteImport
      parentRoute: typeof DashboardBlogRoute
    }
  }
}

interface DashboardBlogRouteChildren {
  DashboardBlogNewRoute: typeof DashboardBlogNewRoute
  DashboardBlogIdEditRoute: typeof DashboardBlogIdEditRoute
}

const DashboardBlogRouteChildren: DashboardBlogRouteChildren = {
  DashboardBlogNewRoute: DashboardBlogNewRoute,
  DashboardBlogIdEditRoute: DashboardBlogIdEditRoute,
}

const DashboardBlogRouteWithChildren = DashboardBlogRoute._addFileChildren(
  DashboardBlogRouteChildren,
)

interface DashboardProjectsRouteChildren {
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardRouteChildren {
  DashboardBlogRoute: typeof DashboardBlogRouteWithChildren
  DashboardExperienceRoute: typeof DashboardExperienceRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBlogRoute: DashboardBlogRouteWithChildren,
  DashboardExperienceRoute: DashboardExperienceRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PUsernameRouteChildren {
  PUsernameProjectsSlugRoute: typeof PUsernameProjectsSlugRoute
}

const PUsernameRouteChildren: PUsernameRouteChildren = {
  PUsernameProjectsSlugRoute: PUsernameProjectsSlugRoute,
}

const PUsernameRouteWithChildren = PUsernameRoute._addFileChildren(
  PUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PUsernameRoute: PUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
